name: Commit Signed
description: a githut workflow action designed to commit signed
branding:
  icon: user-check
  color: green
runs:
  using: composite
  steps:
    - run: curl -s https://raw.githubusercontent.com/slattman/commit-signed/refs/tags/latest/.github/api/createCommitOnBranch.sh | sh -
      shell: bash
