name: commit-signed
on:
  workflow_dispatch:
  workflow_call:
jobs:
  update:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - run: curl https://raw.githubusercontent.com/slattman/commit-signed/refs/tags/latest/.github/api/createCommitOnBranch.sh | sh -
