name: update
on:
  workflow_dispatch:
  push:
jobs:
  update:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
        - uses: actions/checkout@v4.2.2
        - run: gh release delete latest --cleanup-tag -y
        - run: gh release create latest --generate-notes --latest
        - run: gh run delete $(gh run list --json databaseId -q "map(.databaseId)[1]")